pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                bat 'd:'
                bat'cd D:\Program Files\gitcangku\test\simple-java-maven-app@script'
                bat'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                bat 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        
    }
}
